--local M = {
  --"nvim-telescope/telescope.nvim",
  --dependencies = {
    --"nvim-lua/plenary.nvim",
    --'fannheyward/telescope-coc.nvim',
    --"tsakirist/telescope-lazy.nvim"
  --},
  --keys = {
    --{ "<leader>fb", "<cmd>Telescope file_browser grouped=true<cr>", desc = "Filebrowser" },
    --{ "<leader>fz", "<cmd>Telescope zoxide list<cr>", desc = "Zoxide" },
    --{ "<leader>ff", "<cmd>" .. require("util").project_files() .. "<cr>", desc = "Open file" },
    --{ "<leader>fr", "<cmd>Telescope oldfiles prompt_title=Recent<cr>", desc = "Recent files" },
  --}
  --config = function()
    --require("telescope").setup({
      --extensions = {
        --lazy = {
          ---- Optional theme (the extension doesn't set a default theme)
          --theme = "ivy",
          ---- Whether or not to show the icon in the first column
          --show_icon = true,
          ---- Mappings for the actions
          --mappings = {
            --open_in_browser = "<C-o>",
            --open_in_file_browser = "<M-b>",
            --open_in_find_files = "<C-f>",
            --open_in_live_grep = "<C-g>",
            --open_plugins_picker = "<C-b>", -- Works only after having called first another action
            --open_lazy_root_find_files = "<C-r>f",
            --open_lazy_root_live_grep = "<C-r>g",
          --},
          ---- Other telescope configuration options
        --},
        --coc = {
            --theme = 'ivy',
            --prefer_locations = true, -- always use Telescope locations to preview definitions/declarations/implementations etc
        --}
      --},
    --})
    --require('telescope').load_extension('coc')
    --require("telescope").load_extension("lazy")
  --end
--}

--return M
